#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2026 IObundle
#
# SPDX-License-Identifier: GPL-3.0-only

"""Prepare a post-place-and-route netlist for gate-level simulation.

The place-and-route netlist of the top module has the power and ground nets as
additional input ports. The py2hwsw testbenches, which were written for the RTL
version of the module, do not have those ports, so the netlist is renamed and a
wrapper module with the original name, which connects the power and ground nets
to their supply values, is appended to the file.
"""

import argparse
import json
import os
import re
import sys

HEADER = """// SPDX-FileCopyrightText: 2026 IObundle
//
// SPDX-License-Identifier: GPL-3.0-only
"""

DEFAULT_VDD_NETS = ["VPWR"]
DEFAULT_GND_NETS = ["VGND"]


def get_module_header(content, module_name):
    """Return the (port list, port declarations) text of a module.

    The port list is the text between the module name and the ');' that closes
    it, and the port declarations are the 'input'/'output'/'inout' statements
    that follow it (the netlists use the non-ANSI style).
    """
    match = re.search(
        rf"^module\s+{re.escape(module_name)}\s*\(", content, re.MULTILINE
    )
    if not match:
        raise ValueError(f"Module '{module_name}' not found")
    end_of_ports = content.find(");", match.start())
    if end_of_ports < 0:
        raise ValueError(f"End of the port list of '{module_name}' not found")
    port_list = content[match.start() : end_of_ports + 1]

    # The port declarations are the first statements of the module body, one
    # statement per port in the non-ANSI style
    declarations = ""
    rest = content[end_of_ports + 2 :]
    while True:
        statement = re.match(r"\s*(input|output|inout)\b[^;]*;", rest)
        if not statement:
            break
        declarations += statement.group(0)
        rest = rest[statement.end() :]
    if not declarations:
        raise ValueError(f"Port declarations of '{module_name}' not found")
    return port_list, declarations


def get_ports(declarations):
    """Return a list of (name, direction) tuples of a port declaration text"""
    ports = []
    for direction, decl in re.findall(
        r"\b(input|output|inout)\b([^;]*);", declarations, flags=re.DOTALL
    ):
        for name in decl.split(","):
            # Remove the width (e.g. '[DATA_W-1:0]'), if any
            name = re.sub(r"^.*\]", "", name).strip()
            name = re.sub(r"^(input|output|inout)\b", "", name).strip()
            if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name):
                ports.append((name, direction))
    return ports


def prepare_netlist(netlist_path, out_path, vdd_nets, gnd_nets):
    """Write a simulation-ready version of a place-and-route netlist"""
    with open(netlist_path) as f:
        content = f.read()

    design_name = os.path.basename(netlist_path).split(".")[0]
    port_list, declarations = get_module_header(content, design_name)
    ports = get_ports(declarations)

    supply_nets = vdd_nets + gnd_nets
    missing = [net for net in supply_nets if net not in dict(ports)]
    if missing:
        raise ValueError(
            f"Power/ground net(s) {missing} are not ports of '{design_name}'. "
            "Gate-level simulation of this netlist is not supported."
        )

    # Rename the top module, to free its name for the wrapper below
    gate_name = f"{design_name}_gate"
    content = content.replace(f"module {design_name} (", f"module {gate_name} (", 1)

    # The power and ground ports of the netlist are driven by the wrapper. The
    # connections of an inout port must be a net, so the supply values are
    # driven by a continuous assignment of an internal net.
    connections = []
    supply_drivers = []
    for name, _ in ports:
        if name in supply_nets:
            value = "1'b1" if name in vdd_nets else "1'b0"
            net = f"supply_{name.lower()}"
            connections.append(f".{name}({net})")
            supply_drivers.append(f"wire {net} = {value};")
        else:
            connections.append(f".{name}({name})")
    wrapper = (
        f"{HEADER}\n"
        f"// Wrapper generated by py2hwsw for gate-level simulation\n"
        f"{port_list};\n"
        f"{declarations}\n"
        + "".join(f"{driver}\n" for driver in supply_drivers)
        + f" {gate_name} u_gate (\n    "
        + ",\n    ".join(connections)
        + ");\nendmodule\n"
    )

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write(content)
        if not content.endswith("\n"):
            f.write("\n")
        f.write(wrapper)
    return gate_name


def main(netlist_path, out_path, config_path="config.json"):
    vdd_nets, gnd_nets = DEFAULT_VDD_NETS, DEFAULT_GND_NETS
    if os.path.isfile(config_path):
        with open(config_path) as f:
            config = json.load(f)
        vdd_nets = config.get("VDD_NETS", vdd_nets)
        gnd_nets = config.get("GND_NETS", gnd_nets)

    gate_name = prepare_netlist(netlist_path, out_path, vdd_nets, gnd_nets)
    print(
        f"Gate-level simulation netlist written to '{out_path}' (module '{gate_name}')."
    )
    return out_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--netlist", required=True, help="place-and-route netlist")
    parser.add_argument("--out", required=True, help="output netlist file")
    parser.add_argument(
        "--config", default="config.json", help="flow configuration file"
    )
    args = parser.parse_args()

    try:
        main(args.netlist, args.out, args.config)
    except ValueError as e:
        print(f"ERROR: {e}")
        sys.exit(1)
