# SPDX-FileCopyrightText: 2026 IObundle
#
# SPDX-License-Identifier: GPL-3.0-only

# Implementation constraints for the LibreLane/OpenROAD place-and-route steps.
# All values come from the LibreLane configuration (so this file is PDK
# agnostic: sky130*, gf180mcu*, ...).

# Clock
if { [info exists ::env(CLOCK_PORT)] } {
    set clock_port [lindex $::env(CLOCK_PORT) 0]
} else {
    set clock_port __VIRTUAL_CLK__
}
create_clock -name core_clk -period $::env(CLOCK_PERIOD) [get_ports $clock_port]
set_clock_uncertainty $::env(CLOCK_UNCERTAINTY_CONSTRAINT) [get_clocks core_clk]
set_clock_transition $::env(CLOCK_TRANSITION_CONSTRAINT) [get_clocks core_clk]

# I/O budget: a fraction of the clock period is reserved for the paths that
# go outside of the design (chip pads, clock generator, board).
set io_delay [expr $::env(CLOCK_PERIOD) * $::env(IO_DELAY_CONSTRAINT) / 100.0]
set clk_input [get_port $clock_port]
set clk_index [lsearch [all_inputs] $clk_input]
set data_inputs [lreplace [all_inputs] $clk_index $clk_index ""]
set_input_delay $io_delay -clock [get_clocks core_clk] $data_inputs
set_output_delay $io_delay -clock [get_clocks core_clk] [all_outputs]

# Input driver and output load models
if { ![info exists ::env(SYNTH_CLK_DRIVING_CELL)] } {
    set ::env(SYNTH_CLK_DRIVING_CELL) $::env(SYNTH_DRIVING_CELL)
}
set drive_cell [split $::env(SYNTH_DRIVING_CELL) "/"]
set clk_drive_cell [split $::env(SYNTH_CLK_DRIVING_CELL) "/"]
set_driving_cell -lib_cell [lindex $drive_cell 0] -pin [lindex $drive_cell 1] $data_inputs
set_driving_cell -lib_cell [lindex $clk_drive_cell 0] -pin [lindex $clk_drive_cell 1] $clk_input
set_load [expr $::env(OUTPUT_CAP_LOAD) / 1000.0] [all_outputs]

# Design rules (over-constrained on purpose: see signoff.sdc)
# The '*_CONSTRAINT' variables are the ones of the LibreLane configuration,
# generated by py2hwsw. The defaults below are the ones of the sky130 PDK and
# allow this file to also be used with a hand-written configuration file.
if { ![info exists ::env(MAX_FANOUT_CONSTRAINT)] } {
    set ::env(MAX_FANOUT_CONSTRAINT) 4
}
if { ![info exists ::env(MAX_TRANSITION_CONSTRAINT)] } {
    set ::env(MAX_TRANSITION_CONSTRAINT) 1
}
if { ![info exists ::env(MAX_CAPACITANCE_CONSTRAINT)] } {
    set ::env(MAX_CAPACITANCE_CONSTRAINT) 0.15
}
set_max_fanout $::env(MAX_FANOUT_CONSTRAINT) [current_design]
set_max_transition $::env(MAX_TRANSITION_CONSTRAINT) [current_design]
set_max_capacitance $::env(MAX_CAPACITANCE_CONSTRAINT) [current_design]

# Timing derate
set_timing_derate -early [expr 1 - $::env(TIME_DERATING_CONSTRAINT) / 100.0]
set_timing_derate -late [expr 1 + $::env(TIME_DERATING_CONSTRAINT) / 100.0]
