# SPDX-FileCopyrightText: 2026 IObundle
#
# SPDX-License-Identifier: GPL-3.0-only

UART_DIR:=../..

NOCLEAN=-name "pb.pdf"

figures:
	mkdir -p ./figures
	cp -r -u lib/document/figures/* ../figures/bd.odg ./figures

include $(UART_DIR)/document/document.mk
